apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: {{ .Values.namespace }}
type: Opaque
stringData:
  MONGO_USERNAME: {{ .Values.mongodb.username }}
  MONGO_PASSWORD: {{ .Values.mongodb.password }}
