apiVersion: v1
kind: Namespace
metadata:
  name: dev
---
apiVersion: v1
kind: Namespace
metadata:
  name: monitoring
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: dev
data:
  environment: development
  database_url: mongodb-service.dev.svc.cluster.local
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: monitoring
data:
  environment: monitoring
